services:
  mongodb-1:
    image: mongo:latest
    container_name: mongodb-1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=faizal
      - MONGO_INITDB_ROOT_PASSWORD=faizal
      - MONGO_INITDB_DATABASE=admin
    networks:
      - mongodb-network

  monggodb-express:
    image: mongo-express:latest
    container_name: mongodb-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-1
      - ME_CONFIG_MONGODB_ADMINUSERNAME=faizal
      - ME_CONFIG_MONGODB_ADMINPASSWORD=faizal
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_URL=
    # Restart
    #  The restart option is used to specify the restart policy for the container.
    #  The options are:
    #  no: Do not automatically restart the container.
    #  always: Always restart the container if it stops.
    #  unless-stopped: Restart the container unless it is stopped manually.
    #  on-failure: Restart the container only if it exits with a non-zero status.
    #  The default is no.

    restart: always
    networks:
      - mongodb-network
    #  Depends on
    #  The depends_on option is used to specify the order in which services are started.
    #  It does not wait for the service to be fully ready, only for the container to be started.
    depends_on:
      - mongodb-1
    # Resource limits
    #  The deploy option is used to specify resource limits for the container.
    #  The resources option is used to specify the resource limits.
    #  The limits option is used to specify the maximum resource limits.
    #  The reservations option is used to specify the minimum resource limits.
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

    #  Extending services
    #  The extends option is used to extend a service from another service.
    #  The service option is used to specify the service to extend from.
    #  The file option is used to specify the file to extend from.

networks:
  mongodb-network:
    driver: bridge
