pipeline {

    //  Agent Instruction
    //agent any
    agent {
        node {
            // its mean use expression 
            label "wsl || linux && debian"
        }
    }
    // Stages Instruction
    // stages are the main part of the pipeline, if any stage fails, the pipeline will stop and will continue to the post actions
    stages {
        stage('Build') {
            //  Steps Instruction
            // steps are the commands that will be executed in the stage
            // steps are the main part of the stage, if any step fails, the stage will fail and the pipeline will stop
            steps {
                // Script Instruction
                // script is used to run a block of code in the pipeline
                script{
                    for (int i = 0; i < 10; i++) {
                        echo "Hello World ${i}"
                    }
                }
                echo 'Building...'
                // sleep(5)
                sh("cd devops/jenkins/spring-project ; chmod +x mvnw ;  ./mvnw clean compile package")
                echo 'Build completed!'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                // sleep(5)
                sh("cd devops/jenkins/spring-project ; chmod +x mvnw ;  ./mvnw test")
                echo 'Test completed!'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sleep(5)
                echo 'Deploy completed!'
            }
        }
    }

    // Post Actions Instruction
    post {
        always {
            echo 'This will always run after the stages.'
        }
        success {
            echo 'This will run only if the pipeline is successful.'
        }
        failure {
            echo 'This will run only if the pipeline fails.'
        }
        cleanup {
            echo 'This will run after the pipeline, regardless of success or failure.'
        }
    }
}