pipeline {

    // Environment Instruction
    // environment is used to set environment variables for the pipeline
    // environment {
    //     MY_ENV_VAR = 'my_value'
    // }

    environment {
       AUTHOR = 'John Doe'
    } 


    //  Agent Instruction
    //agent any
    // agent {
    //     node {
    //         // its mean use expression 
    //         label "wsl || linux && debian"
    //     }
    // }
    // if agent set the none, we can set each stage with different agent
    agent none
    
    // Stages Instruction
    // stages are the main part of the pipeline, if any stage fails, the pipeline will stop and will continue to the post actions
    stages {
        stage('Build') {
            agent {
                node {
                    // its mean use expression 
                    label "wsl || linux && debian"
                }
            }
            //  Steps Instruction
            // steps are the commands that will be executed in the stage
            // steps are the main part of the stage, if any step fails, the stage will fail and the pipeline will stop
            steps {
                // Script Instruction
                // script is used to run a block of code in the pipeline
                script{
                    for (int i = 0; i < 10; i++) {
                        echo "Hello World ${i}"
                    }
                    // Pipeline utility steps
                    // in Jenkins web UI, you need to install the plugin "Pipeline Utility Steps" to use this function
                    // for all utility steps, you can see in doc https://www.jenkins.io/doc/pipeline/steps/pipeline-utility-steps/
                    def data = [
                        "firstName" : "John",
                        "lastName" : "Doe"
                    ]
                    writeJSON (file: 'data.json', json: data)
                    
                }
                echo 'Building...'
                // sleep(5)
                sh("cd devops/jenkins/spring-project ; chmod +x mvnw ;  ./mvnw clean compile package")
                echo 'Build completed! By ${AUTHOR}'
            }
        }
        stage('Test') {
            agent {
                node {
                    // its mean use expression 
                    label "wsl || linux && debian"
                }
            }
            steps {
                echo 'Testing...'
                // sleep(5)
                sh("cd devops/jenkins/spring-project ; chmod +x mvnw ;  ./mvnw test")
                echo 'Test completed!'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sleep(5)
                echo 'Deploy completed!'
            }
        }
    }

    // Post Actions Instruction
    post {
        always {
            echo 'This will always run after the stages.'
        }
        success {
            echo 'This will run only if the pipeline is successful.'
        }
        failure {
            echo 'This will run only if the pipeline fails.'
        }
        cleanup {
            echo 'This will run after the pipeline, regardless of success or failure.'
        }
    }
}